### ISSUE TITLE
Error on "gem install rails"

### ISSUE THREAD

**Issue by betocustom** [aprodeweb/rubyonrails.org.es#4]
Hi, i'm trying install rails but the installation finished with a error:

Microsoft Windows [Versión 6.1.7601]
Copyright (c) 2009 Microsoft Corporation. Reservados todos los derechos.

C:\>gem install rails
Fetching: hike-1.2.3.gem (100%)
Successfully installed hike-1.2.3
Fetching: rack-1.5.2.gem (100%)
Successfully installed rack-1.5.2
Fetching: tilt-1.4.1.gem (100%)
Successfully installed tilt-1.4.1
Fetching: sprockets-2.12.1.gem (100%)
Successfully installed sprockets-2.12.1
Fetching: erubis-2.7.0.gem (100%)
Successfully installed erubis-2.7.0
Fetching: thread_safe-0.3.4.gem (100%)
Successfully installed thread_safe-0.3.4
Fetching: minitest-5.4.1.gem (100%)
Successfully installed minitest-5.4.1
Fetching: tzinfo-1.2.2.gem (100%)
Successfully installed tzinfo-1.2.2
Fetching: i18n-0.6.11.gem (100%)
Successfully installed i18n-0.6.11
Fetching: activesupport-4.1.5.gem (100%)
Successfully installed activesupport-4.1.5
Fetching: actionview-4.1.5.gem (100%)
Successfully installed actionview-4.1.5
Fetching: rack-test-0.6.2.gem (100%)
Successfully installed rack-test-0.6.2
Fetching: actionpack-4.1.5.gem (100%)
Successfully installed actionpack-4.1.5
Fetching: sprockets-rails-2.1.3.gem (100%)
Successfully installed sprockets-rails-2.1.3
Fetching: thor-0.19.1.gem (100%)
Successfully installed thor-0.19.1
Fetching: railties-4.1.5.gem (100%)
Successfully installed railties-4.1.5
Fetching: mime-types-1.25.1.gem (100%)
Successfully installed mime-types-1.25.1
Fetching: polyglot-0.3.5.gem (100%)
Successfully installed polyglot-0.3.5
Fetching: treetop-1.4.15.gem (100%)
Successfully installed treetop-1.4.15
Fetching: mail-2.5.4.gem (100%)
Successfully installed mail-2.5.4
Fetching: actionmailer-4.1.5.gem (100%)
Successfully installed actionmailer-4.1.5
Fetching: arel-5.0.1.20140414130214.gem (100%)
Successfully installed arel-5.0.1.20140414130214
Fetching: activemodel-4.1.5.gem (100%)
Successfully installed activemodel-4.1.5
Fetching: activerecord-4.1.5.gem (100%)
Successfully installed activerecord-4.1.5
Fetching: rails-4.1.5.gem (100%)
Successfully installed rails-4.1.5
Parsing documentation for hike-1.2.3
Installing ri documentation for hike-1.2.3
Parsing documentation for rack-1.5.2
Installing ri documentation for rack-1.5.2
Parsing documentation for tilt-1.4.1
Installing ri documentation for tilt-1.4.1
Parsing documentation for sprockets-2.12.1
Installing ri documentation for sprockets-2.12.1
Parsing documentation for erubis-2.7.0
Installing ri documentation for erubis-2.7.0
Parsing documentation for thread_safe-0.3.4
Installing ri documentation for thread_safe-0.3.4
Parsing documentation for minitest-5.4.1
Installing ri documentation for minitest-5.4.1
Parsing documentation for tzinfo-1.2.2
Installing ri documentation for tzinfo-1.2.2
Parsing documentation for i18n-0.6.11
Installing ri documentation for i18n-0.6.11
Parsing documentation for activesupport-4.1.5
unable to convert "\x80" from ASCII-8BIT to UTF-8 for lib/active_support/values/
unicode_tables.dat, skipping
Installing ri documentation for activesupport-4.1.5
Parsing documentation for actionview-4.1.5
Installing ri documentation for actionview-4.1.5
Parsing documentation for rack-test-0.6.2
Installing ri documentation for rack-test-0.6.2
Parsing documentation for actionpack-4.1.5
Installing ri documentation for actionpack-4.1.5
ERROR:  While executing gem ... (Errno::EINVAL)
    Invalid argument - ./ActionDispatch/Routing/Mapper/Scoping/:

C:\>

**Comment by oinak** [comment]
We have updated intrusctions for windows, and tested them.
Can you try now and give it another try?
Thanks for reporting

**Comment by oinak** [comment]
If you (or anyone) have problems with the new instructions, please opena nwe issue with the error
